sudo: false
language: php

jobs:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
      env: COMPOSER_OPTION=--ignore-platform-reqs

before_script:
  - travis_retry composer install --no-interaction $COMPOSER_OPTION

script:
  - vendor/bin/phpunit
